version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "products-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5mhdsnoyikm9"
s3_prefix = "products-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
